[server]
#port               = 8080
path               = /opt/foxtails/http.sock
log-level          = 0
num-workers        = 4
max-connections    = 512
# Keep alive connection timeout is measured in seconds
keep-alive-timeout = 75

[app]
root=./example
