# Methods		Route/Mountpoint		Type		path
ALL             /                       alias       /index.html
ALL             /index.html             reroute     /
ALL             /api                    proxy       http://127.0.0.1:4001
